### ISSUE TITLE
Field gets messsed up when modifying another field using object.save()

### ISSUE THREAD

**Issue by szucsd135** [raagin/django-tablefield#1]
the code:
`mydron = Dron.objects.get(url=url)`
`mydron.viewcount=mydron.viewcount+1`
`mydron.save()`

the database cell before:
`{"data": [["Name", "value"], ["Name", "value"]], "first_row_is_table_header": false, "first_col_is_header": false, "mergeCells": [], "cellsMeta": []}`

the database cell after:
`"{\"data\": [[\"Name\", \"value\"], [\"Name\", \"value\"]], \"first_row_is_table_header\": false, \"first_col_is_header\": false, \"mergeCells\": [], \"cellsMeta\": [], \"renderer\": \"html\"}"`

**Comment by raagin** [comment]
Let's try this https://github.com/raagin/django-tablefield/commit/e6963d88dbe90454689c2d06ded710beb4710799
If it's helps i will make package

**Comment by szucsd135** [comment]
It doesn't seem to be working.

**Comment by raagin** [comment]
> It doesn't seem to be working.

Have you reinstalled the module? pip install git+https://github.com/raagin/django-tablefield.git
